# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "Puppetlabs CentOS 6.4 x86_64"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"

  # We're going to need some memory for this
  config.vm.customize ["modifyvm", :id, "--memory", 2048]
  config.vm.host_name = "vagrant-load-test"
  config.vm.network :hostonly, "192.168.33.10"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "base.pp"
  end

end
