# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "Puppetlabs CentOS 6.3 x86_64"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-63-x64.box"

  config.vm.host_name = "vagrant-zend"
  config.vm.network :hostonly, "192.168.33.10"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "base.pp"
    puppet.module_path    = "../puppet-modules"
  end

  config.vm.forward_port 80, 8080
  # Access the Zend Server UI at http://localhost:10082/
  config.vm.forward_port 10081, 10082

end
